name: Feature Request or Enhancement
description: 新功能/改进建议
title: "[Feature] "
labels: ["feature"]
body:

  - type: textarea
    id: feature
    attributes:
      label: 简述
      description: 简述一下这个新功能/改进吧
    validations:
      required: true

  - type: textarea
    id: detail
    attributes:
      label: 细节
      description: 详细描述一下具体细节
    validations:
      required: true